using UnityEngine;
using UnityEngine.InputSystem;
using Blocks.Gameplay.Core;

public class BirdVehicle : BaseVehicle
{
    [Header("Input Integration")]
    public Vector2Event moveInputEvent;
    public Transform cameraTransform;
    public Vector2Event lookInputEvent;

    [Header("Flight Control Surfaces")]
    [Range(0.01f, 2f)]
    public float controlSensitivity = 1f;
    public float pitchSpeed = 50f;
    public float yawSpeed = 30f;
    public float rollSpeed = 60f;
    [Tooltip("Prevents sideways drifting (simulates the tail stabilizer).")]
    public float lateralGrip = 5f;

    [Header("Flight & Gliding (Elytra Style)")]
    [Tooltip("How much falling speed is converted into forward speed when looking down.")]
    public float glideEfficiency = 2f;
    [Tooltip("Standard lift generated by moving forward.")]
    public float flightLift = 0.05f;
    [Tooltip("Drag applied to cap maximum flight speed.")]
    public float flightDrag = 0.02f;
    
    [Header("Flight Abilities")]
    public float boostThrust = 8000f;
    public float hoverForce = 1500f;

    // Local inputs for flight
    private float pitchInput = 0f;
    private float yawInput = 0f;
    private float rollInput = 0f;

    [Header("State")]
    public bool isWalking = false;
    private bool wasWalking = true;
    public float walkEngageDistance = 2.5f;
    public LayerMask groundLayer;

    [Header("Stamina System")]
    public float maxStamina = 100f;
    public float currentStamina = 100f;
    public float staminaRegenRate = 50f;    // Stamina gained per second while walking
    public float boostStaminaCost = 30f;    // Stamina drained per second while boosting
    public float hoverStaminaCost = 20f;    // Stamina drained per second while hovering

    [Header("Hover / Leg Physics")]
    public Transform[] legPoints;
    public float hoverHeight = 1.0f;
    public float springConstant = 5000f;
    public float dampingConstant = 500f;

    [Header("Walking Movement")]
    public float walkAcceleration = 3000f;
    public float rotationTorque = 2000f;
    public float walkingDrag = 3f; 
    public float walkingAngularDrag = 5f;
    public float uprightTorque = 5000f;
    public float uprightDamping = 500f;

    [Header("Visual Effects")]
    [Tooltip("Assign the Trail Renderers located on the wingtips.")]
    public TrailRenderer[] wingTrails;
    [Tooltip("How fast the bird must be flying to generate vapor trails.")]
    public float minTrailSpeed = 20f;

    // Cache inputs
    private Vector2 moveInput;
    private bool isBoostPressed;
    private bool isHoverPressed;

    protected override void Awake()
    {
        base.Awake();
        currentStamina = maxStamina;
    }

    protected override void ProcessVehicleInput()
    {
        // 1. Move input (WASD) - Used for walking, and A/D is used for flight roll
        moveInput = moveInputEvent != null ? moveInputEvent.LastValue : Vector2.zero;
        rollInput = moveInput.x * controlSensitivity;
        
        // 2. Look input (Mouse) - Used for Pitch and Yaw during flight
        Vector2 lookInput = lookInputEvent != null ? lookInputEvent.LastValue : Vector2.zero;
        yawInput = lookInput.x * controlSensitivity;
        pitchInput = lookInput.y * controlSensitivity; 

        if (cameraTransform == null && Camera.main != null)
        {
            cameraTransform = Camera.main.transform;
        }

        // Capture Ability Inputs
        if (Keyboard.current != null)
        {
            isBoostPressed = Keyboard.current.shiftKey.isPressed;
            isHoverPressed = Keyboard.current.spaceKey.isPressed;
        }
    }

    protected override void ApplyAlwaysPhysics()
    {
        CheckWalkingState();

        if (isWalking)
        {
            // MOVED BACK: The bird will now balance and stand even when empty!
            ApplyUprightStabilization();
            ApplyHoverLegs();

            currentStamina = Mathf.Min(maxStamina, currentStamina + (staminaRegenRate * Time.fixedDeltaTime));
        }
    }
    
    protected override void Update()
    {
        // 1. Run the base vehicle update (UI, Interactions, Camera)
        base.Update();
        
        if (!IsSpawned) return;

        // 2. Control the vapor trails (Runs for all clients so everyone sees them)
        float currentSpeed = rb.linearVelocity.magnitude;
        bool shouldShowTrails = !isWalking && currentSpeed > minTrailSpeed;

        foreach (TrailRenderer trail in wingTrails)
        {
            if (trail != null)
            {
                // emitting controls whether new trail segments are drawn
                trail.emitting = shouldShowTrails;
            }
        }
    }

    protected override void ApplyVehiclePhysics()
    {
        CheckWalkingState();

        // --- NEW: CINEMACHINE CAMERA SWITCHING ---
        if (wasWalking && !isWalking)
        {
            // We just took off! Switch to Flight Camera and override targets to the bird
            SetDriverCameraMode("FlightMode", true);
        }
        else if (!wasWalking && isWalking)
        {
            // We just landed! Switch to FreeLook and remove the overrides
            SetDriverCameraMode("FreeLook", false);
        }
        
        wasWalking = isWalking; // Remember the state for next frame
        // -----------------------------------------

        ApplyFlightAbilities();

        if (isWalking)
        {
            // ADDED BACK: Balance and stamina regen for the driver!
            ApplyUprightStabilization();
            currentStamina = Mathf.Min(maxStamina, currentStamina + (staminaRegenRate * Time.fixedDeltaTime));

            ApplyWalkingMovement();
            ApplyRotation();
            ApplyHoverLegs();
        }
        else
        {
            ApplyFlightPhysics();
        }
    }

    private void CheckWalkingState()
    {
        bool groundDetected = false;

        foreach (Transform leg in legPoints)
        {
            if (Physics.Raycast(leg.position, Vector3.down, out RaycastHit hit, walkEngageDistance, groundLayer))
            {
                groundDetected = true;
                break;
            }
        }

        isWalking = groundDetected;

        if (isWalking)
        {
            rb.linearDamping = walkingDrag; 
            rb.angularDamping = walkingAngularDrag;
        }
        else
        {
            // Free aerodynamic movement in the air
            rb.linearDamping = 0.1f;
            rb.angularDamping = 1f; // Slightly higher angular drag prevents violent spinning in air
        }
    }

    private void ApplyFlightPhysics()
    {
        Vector3 localVelocity = transform.InverseTransformDirection(rb.linearVelocity);
        float forwardSpeed = Mathf.Max(0, localVelocity.z); 
        float totalSpeed = rb.linearVelocity.magnitude;

        // 1. Elytra Glide Mechanic (Convert falling into forward speed)
        if (rb.linearVelocity.y < 0) 
        {
            float fallSpeed = -rb.linearVelocity.y;
            // The more we pitch down (negative local velocity Y), the more forward boost we get
            float pitchDownFactor = Mathf.Clamp01(-localVelocity.y / Mathf.Max(1f, totalSpeed));
            rb.AddForce(transform.forward * (fallSpeed * pitchDownFactor * glideEfficiency), ForceMode.Acceleration);
        }

        // 2. Standard Lift & Drag
        float liftForce = flightLift * (forwardSpeed * forwardSpeed);
        rb.AddForce(transform.up * liftForce);

        float dragForce = flightDrag * (totalSpeed * totalSpeed);
        if (totalSpeed > 0.1f)
        {
            rb.AddForce(-rb.linearVelocity.normalized * dragForce);
        }

        // 3. Airplane-Style Steering (Pitch, Yaw, Roll)
        // Control authority scales with speed so you can't turn instantly if standing still in mid-air
        float controlAuthority = Mathf.Clamp(forwardSpeed / 10f, 0.1f, 1f); 
        
        rb.AddTorque(transform.right * -pitchInput * pitchSpeed * controlAuthority, ForceMode.Acceleration);
        rb.AddTorque(transform.up * yawInput * yawSpeed * controlAuthority, ForceMode.Acceleration);
        rb.AddTorque(transform.forward * -rollInput * rollSpeed * controlAuthority, ForceMode.Acceleration);

        // 4. Aerodynamic Grip (Prevents sideways drifting)
        Vector3 sidewaysVelocity = Vector3.Project(rb.linearVelocity, transform.right);
        rb.AddForce(-sidewaysVelocity * lateralGrip, ForceMode.Acceleration);
    }

    private void ApplyFlightAbilities()
    {
        // HOVER (Spacebar)
        if (isHoverPressed && currentStamina > 0)
        {
            currentStamina -= hoverStaminaCost * Time.fixedDeltaTime;
            
            // Counteract gravity to hover in place
            Vector3 hoverCounterForce = -Physics.gravity + (Vector3.up * hoverForce);
            rb.AddForce(hoverCounterForce, ForceMode.Acceleration);

            // Heavily dampen existing velocity so you stop and hover quickly
            rb.linearVelocity = Vector3.Lerp(rb.linearVelocity, Vector3.zero, Time.fixedDeltaTime * 2f);
        }
        
        // BOOST (Shift)
        if (isBoostPressed && currentStamina > 0 && !isHoverPressed)
        {
            currentStamina -= boostStaminaCost * Time.fixedDeltaTime;
            
            // Push forward and slightly upward
            Vector3 boostDir = (transform.forward + (Vector3.up * 0.25f)).normalized;
            rb.AddForce(boostDir * boostThrust);
            Debug.Log($"boosting: {currentStamina}");
        }
    }

    // --- Walking Methods (Unchanged) ---
    private void ApplyHoverLegs()
    {
        foreach (Transform point in legPoints)
        {
            if (Physics.Raycast(point.position, Vector3.down, out RaycastHit hit, hoverHeight * 2f, groundLayer))
            {
                Vector3 pointVelocity = rb.GetPointVelocity(point.position);
                float compression = hoverHeight - hit.distance;
                float upwardSpeed = Vector3.Dot(pointVelocity, Vector3.up);

                float hoverForce = (compression * springConstant) - (upwardSpeed * dampingConstant);
                rb.AddForceAtPosition(Vector3.up * hoverForce, point.position);
            }
        }
    }

    private void ApplyUprightStabilization()
    {
        Vector3 cross = Vector3.Cross(transform.up, Vector3.up);
        Vector3 torque = (cross * uprightTorque) - (rb.angularVelocity * uprightDamping);
        rb.AddTorque(torque, ForceMode.Acceleration);
    }

    private void ApplyWalkingMovement()
    {
        if (moveInput.sqrMagnitude < 0.01f) return;

        Vector3 moveDirection;
        if (cameraTransform != null)
        {
            Vector3 camForward = cameraTransform.forward;
            Vector3 camRight = cameraTransform.right;
            camForward.y = 0;
            camRight.y = 0;
            moveDirection = (camForward.normalized * moveInput.y) + (camRight.normalized * moveInput.x);
        }
        else
        {
            moveDirection = (transform.forward * moveInput.y) + (transform.right * moveInput.x);
        }
        rb.AddForce(moveDirection.normalized * walkAcceleration, ForceMode.Acceleration);
    }

    private void ApplyRotation()
    {
        if (cameraTransform != null)
        {
            Vector3 targetForward = cameraTransform.forward;
            targetForward.y = 0;
            if (targetForward.sqrMagnitude > 0.001f)
            {
                Quaternion targetRotation = Quaternion.LookRotation(targetForward, Vector3.up);
                float angle = Quaternion.Angle(transform.rotation, targetRotation);
                if (angle > 1f)
                {
                    Vector3 cross = Vector3.Cross(transform.forward, targetForward.normalized);
                    rb.AddTorque(cross * rotationTorque, ForceMode.Acceleration);
                }
            }
        }
    }

    
}