using UnityEngine;
using UnityEngine.InputSystem;
using Blocks.Gameplay.Core;

public class BirdVehicle : BaseVehicle
{
    [Header("Input Integration")]
    public Vector2Event moveInputEvent;
    public Transform cameraTransform;
    public Vector2Event lookInputEvent;

    [Header("Virtual Joystick (Mouse Aim)")]
    [Tooltip("How fast the invisible cursor moves when you move the mouse.")]
    public float cursorSensitivity = 2f;
    [Tooltip("How fast the bird naturally levels out when you let go of the mouse.")]
    public float autoCenterSpeed = 3f;

    [Header("Virtual Joystick UI")]
    [Tooltip("The canvas containing the flight UI.")]
    public Canvas flightCanvas;
    [Tooltip("The RectTransform of the crosshair image.")]
    public RectTransform crosshairRect;
    [Tooltip("How far (in pixels) the crosshair can move from the center of the screen.")]
    public float crosshairRadius = 300f;
    
    private Vector2 virtualCursor = Vector2.zero;

    [Header("Flight Control Surfaces")]
    [Range(0.01f, 2f)]
    public float controlSensitivity = 1f;
    public float pitchSpeed = 50f;
    public float yawSpeed = 30f;
    public float rollSpeed = 60f;
    [Tooltip("Prevents sideways drifting (simulates the tail stabilizer).")]
    public float lateralGrip = 5f;
    public float flightAngularDamping = 4f;
    public float flightLinearDamping = 0.1f;

    [Header("Flight & Gliding (Elytra Style)")]
    [Tooltip("How much falling speed is converted into forward speed when looking down.")]
    public float glideEfficiency = 2f;
    [Tooltip("Standard lift generated by moving forward.")]
    public float flightLift = 0.05f;
    [Tooltip("Drag applied to cap maximum flight speed.")]
    public float flightDrag = 0.02f;
    
    [Header("Flight Abilities")]
    public float boostThrust = 8000f;
    public float hoverForce = 1500f;

    [Header("Stall Mechanics")]
    [Tooltip("Forward speed where the bird loses control and falls.")]
    public float stallSpeed = 5f;
    [Tooltip("Forward speed required to regain aerodynamic control.")]
    public float recoverySpeed = 20f;
    public bool isStalled = false;

    // Local inputs for flight
    private float pitchInput = 0f;
    private float yawInput = 0f;
    private float rollInput = 0f;

    [Header("State")]
    public bool isWalking = false;
    private bool wasWalking = true;
    public float walkEngageDistance = 2.5f;
    public LayerMask groundLayer;

    [Header("Stamina System")]
    public float maxStamina = 100f;
    public float currentStamina = 100f;
    public float staminaRegenRate = 50f;    // Stamina gained per second while walking
    public float boostStaminaCost = 30f;    // Stamina drained per second while boosting
    public float hoverStaminaCost = 20f;    // Stamina drained per second while hovering

    [Header("Hover / Leg Physics")]
    public Transform[] legPoints;
    public float hoverHeight = 1.0f;
    public float springConstant = 5000f;
    public float dampingConstant = 500f;

    [Header("Walking Movement")]
    public float walkAcceleration = 3000f;
    public float rotationTorque = 2000f;
    public float walkingDrag = 3f; 
    public float walkingAngularDrag = 5f;
    public float uprightTorque = 5000f;
    public float uprightDamping = 500f;

    [Header("Visual Effects")]
    [Tooltip("Assign the Trail Renderers located on the wingtips.")]
    public TrailRenderer[] wingTrails;
    [Tooltip("How fast the bird must be flying to generate vapor trails.")]
    public float minTrailSpeed = 20f;

    [Header("Wing Animation (Tuck)")]
    public Transform leftWing;
    public Transform rightWing;
    [Tooltip("The local rotation of the wings when flying normally.")]
    public Vector3 leftWingOpenRotation = Vector3.zero;
    public Vector3 rightWingOpenRotation = Vector3.zero;
    [Tooltip("The local rotation of the wings when tucked back (adjust axis depending on your model).")]
    public Vector3 leftWingTuckedRotation = new Vector3(0, 60, 0); 
    public Vector3 rightWingTuckedRotation = new Vector3(0, -60, 0);
    [Tooltip("How fast the wings snap in and out.")]
    public float wingTuckSpeed = 12f;

    // Cache inputs
    private Vector2 moveInput;
    private bool isBoostPressed;
    private bool isHoverPressed;
    private bool tuckToggle = false;

    protected override void Awake()
    {
        base.Awake();
        currentStamina = maxStamina;
    }

    protected override void ProcessVehicleInput()
    {
        // 1. Move input (A/D is used for flight roll)
        moveInput = moveInputEvent != null ? moveInputEvent.LastValue : Vector2.zero;
        rollInput = moveInput.x * controlSensitivity;
        
        // 2. Look input (Mouse Delta)
        Vector2 lookDelta = lookInputEvent != null ? lookInputEvent.LastValue : Vector2.zero;

        if (isWalking)
        {
            // WALKING: Use direct, snappy input for ground control
            yawInput = lookDelta.x * controlSensitivity;
            pitchInput = lookDelta.y * controlSensitivity;
            virtualCursor = Vector2.zero; // Keep cursor centered while grounded
        }
        else
        {
            // FLYING: Accumulate the mouse movement into a virtual cursor position
            if (lookDelta.sqrMagnitude > 0.001f)
            {
                virtualCursor += lookDelta * cursorSensitivity * Time.deltaTime;
                
                // Clamp it like a physical joystick (-1 to 1)
                virtualCursor.x = Mathf.Clamp(virtualCursor.x, -1f, 1f);
                virtualCursor.y = Mathf.Clamp(virtualCursor.y, -1f, 1f);
            }
            else
            {
                // Smoothly pull the cursor back to the center if hands are off the mouse
                virtualCursor = Vector2.Lerp(virtualCursor, Vector2.zero, Time.deltaTime * autoCenterSpeed);
            }

            // Pass the cursor's coordinates to your existing physics logic!
            yawInput = virtualCursor.x;
            pitchInput = virtualCursor.y;
        }

        if (cameraTransform == null && Camera.main != null)
        {
            cameraTransform = Camera.main.transform;
        }

        if (Keyboard.current != null)
        {
            isBoostPressed = Keyboard.current.shiftKey.isPressed;
            isHoverPressed = Keyboard.current.spaceKey.isPressed;

            if(Keyboard.current.ctrlKey.wasPressedThisFrame)
            {
                tuckToggle = !tuckToggle;
            }
        }

        // --- VIRTUAL JOYSTICK UI UPDATE ---
        if (flightCanvas != null)
        {
            // Only show the crosshair if we are the driver and currently flying
            bool shouldShowUI = isLocalPlayerDriver && !isWalking;
            if (flightCanvas.gameObject.activeSelf != shouldShowUI)
            {
                flightCanvas.gameObject.SetActive(shouldShowUI);
            }
        }

        if (crosshairRect != null && !isWalking)
        {
            // Map the -1 to 1 virtual cursor directly to screen pixels
            crosshairRect.anchoredPosition = virtualCursor * crosshairRadius;
        }
    }

    protected override void ApplyAlwaysPhysics()
    {
        CheckWalkingState();

        if (isWalking)
        {
            // MOVED BACK: The bird will now balance and stand even when empty!
            ApplyUprightStabilization();
            ApplyHoverLegs();

            currentStamina = Mathf.Min(maxStamina, currentStamina + (staminaRegenRate * Time.fixedDeltaTime));
        }
    }
    
    protected override void Update()
    {
        // 1. Run the base vehicle update (UI, Interactions, Camera)
        base.Update();
        
        if (!IsSpawned) return;

        // 2. Control the vapor trails (Runs for all clients so everyone sees them)
        float currentSpeed = rb.linearVelocity.magnitude;
        bool shouldShowTrails = !isWalking && currentSpeed > minTrailSpeed;

        foreach (TrailRenderer trail in wingTrails)
        {
            if (trail != null)
            {
                // emitting controls whether new trail segments are drawn
                trail.emitting = shouldShowTrails;
            }
        }

        // 3. Procedurally Animate Wings & Colliders
        if (leftWing != null && rightWing != null)
        {
            // Pick our target angles based on the Right-Click tuck button
            Vector3 targetLeft = tuckToggle ? leftWingTuckedRotation : leftWingOpenRotation;
            Vector3 targetRight = tuckToggle ? rightWingTuckedRotation : rightWingOpenRotation;

            // Smoothly rotate the wing transforms toward the target angles
            leftWing.localRotation = Quaternion.Lerp(leftWing.localRotation, Quaternion.Euler(targetLeft), Time.deltaTime * wingTuckSpeed);
            rightWing.localRotation = Quaternion.Lerp(rightWing.localRotation, Quaternion.Euler(targetRight), Time.deltaTime * wingTuckSpeed);
        }
    }

    protected override void ApplyVehiclePhysics()
    {
        CheckWalkingState();

        // --- CINEMACHINE CAMERA SWITCHING ---
        if (cachedCamController != null)
        {
            if (wasWalking && !isWalking)
            {
                // We just took off! ONLY switch the camera mode. Do NOT touch targets!
                cachedCamController.SwitchCameraMode("FlightMode");
            }
            else if (!wasWalking && isWalking)
            {
                // We just landed! ONLY switch the camera mode. Do NOT touch targets!
                cachedCamController.SwitchCameraMode("FreeLook");
                cachedCamController.SetHorizontalLookAngle(transform.eulerAngles.y);
            }
        }
        
        wasWalking = isWalking; 
        // -----------------------------------------
        
        wasWalking = isWalking; // Remember the state for next frame
        // -----------------------------------------

        ApplyFlightAbilities();

        if (isWalking)
        {
            // ADDED BACK: Balance and stamina regen for the driver!
            ApplyUprightStabilization();
            currentStamina = Mathf.Min(maxStamina, currentStamina + (staminaRegenRate * Time.fixedDeltaTime));

            ApplyWalkingMovement();
            ApplyRotation();
            ApplyHoverLegs();
        }
        else
        {
            ApplyFlightPhysics();
        }
    }

    private void CheckWalkingState()
    {
        bool groundDetected = false;

        foreach (Transform leg in legPoints)
        {
            if (Physics.Raycast(leg.position, Vector3.down, out RaycastHit hit, walkEngageDistance, groundLayer))
            {
                groundDetected = true;
                break;
            }
        }

        isWalking = groundDetected;

        if (isWalking)
        {
            rb.linearDamping = walkingDrag; 
            rb.angularDamping = walkingAngularDrag;
        }
        else
        {
            // Free aerodynamic movement in the air
            rb.linearDamping = flightLinearDamping;
            rb.angularDamping = flightAngularDamping; // Slightly higher angular drag prevents violent spinning in air
        }
    }

    private void ApplyFlightPhysics()
    {
        Vector3 localVelocity = transform.InverseTransformDirection(rb.linearVelocity);
        float forwardSpeed = Mathf.Max(0, localVelocity.z); 
        float totalSpeed = rb.linearVelocity.magnitude;

        // ONLY apply lift, drag, and glide if the wings are out!
        if (!tuckToggle)
        {
            // 1. Elytra Glide Mechanic 
            if (rb.linearVelocity.y < 0) 
            {
                float fallSpeed = -rb.linearVelocity.y;
                float pitchDownFactor = Mathf.Clamp01(-localVelocity.y / Mathf.Max(1f, totalSpeed));
                rb.AddForce(transform.forward * (fallSpeed * pitchDownFactor * glideEfficiency), ForceMode.Acceleration);
            }

            // 2. Standard Lift & Drag
            float liftForce = flightLift * (forwardSpeed * forwardSpeed);
            rb.AddForce(transform.up * liftForce);

            float dragForce = flightDrag * (totalSpeed * totalSpeed);
            if (totalSpeed > 0.1f)
            {
                rb.AddForce(-rb.linearVelocity.normalized * dragForce);
            }
        }

        // 3. Airplane-Style Steering (Pitch, Yaw, Roll)
        // We leave this OUTSIDE the tuck check so you can aim your dive while tucked!
        float controlAuthority = Mathf.Clamp(forwardSpeed / 10f, 0.1f, 1f); 
        
        rb.AddTorque(transform.right * -pitchInput * pitchSpeed * controlAuthority, ForceMode.Acceleration);
        rb.AddTorque(transform.up * yawInput * yawSpeed * controlAuthority, ForceMode.Acceleration);
        rb.AddTorque(transform.forward * -rollInput * rollSpeed * controlAuthority, ForceMode.Acceleration);

        // ONLY apply Aerodynamic Grip and Stall mechanics if the wings are out!
        if (!tuckToggle)
        {
            // 4. Arcade Aerodynamic Grip (State-Based Hysteresis Stall)
            if (!isStalled && forwardSpeed < stallSpeed)
            {
                isStalled = true; 
            }
            else if (isStalled && forwardSpeed > recoverySpeed)
            {
                isStalled = false; 
            }

            float gripAuthority = isStalled ? 0f : 1f;

            // Apply Local Aerodynamics
            localVelocity.x = Mathf.Lerp(localVelocity.x, 0, Time.fixedDeltaTime * lateralGrip * gripAuthority);
            localVelocity.y = Mathf.Lerp(localVelocity.y, 0, Time.fixedDeltaTime * lateralGrip * gripAuthority);

            // Turn Speed Bleed
            if (!isStalled)
            {
                float alignment = Vector3.Dot(rb.linearVelocity.normalized, transform.forward);
                float speedRetention = Mathf.Lerp(0.95f, 1f, Mathf.Clamp01(alignment));
                localVelocity.z *= speedRetention;
            }

            rb.linearVelocity = transform.TransformDirection(localVelocity);
            
            // The Rock Drop
            if (isStalled)
            {
                Vector3 worldHorizontalVel = new Vector3(rb.linearVelocity.x, 0, rb.linearVelocity.z);
                rb.AddForce(-worldHorizontalVel * 5f, ForceMode.Acceleration);
                rb.AddForce(Vector3.down * 25f, ForceMode.Acceleration);
            }
        }
    }

    private void ApplyFlightAbilities()
    {
        // HOVER (Spacebar)
        if (isHoverPressed && currentStamina > 0)
        {
            currentStamina -= hoverStaminaCost * Time.fixedDeltaTime;
            
            // Counteract gravity to hover in place
            Vector3 hoverCounterForce = -Physics.gravity + (Vector3.up * hoverForce);
            rb.AddForce(hoverCounterForce, ForceMode.Acceleration);

            // Heavily dampen existing velocity so you stop and hover quickly
            rb.linearVelocity = Vector3.Lerp(rb.linearVelocity, Vector3.zero, Time.fixedDeltaTime * 2f);
        }
        
        // BOOST (Shift)
        if (isBoostPressed && currentStamina > 0 && !isHoverPressed)
        {
            currentStamina -= boostStaminaCost * Time.fixedDeltaTime;
            
            // Push forward and slightly upward
            Vector3 boostDir = (transform.forward + (Vector3.up * 0.25f)).normalized;
            rb.AddForce(boostDir * boostThrust);
            Debug.Log($"boosting: {currentStamina}");
        }
    }

    // --- Walking Methods (Unchanged) ---
    private void ApplyHoverLegs()
    {
        foreach (Transform point in legPoints)
        {
            if (Physics.Raycast(point.position, Vector3.down, out RaycastHit hit, hoverHeight * 2f, groundLayer))
            {
                Vector3 pointVelocity = rb.GetPointVelocity(point.position);
                float compression = hoverHeight - hit.distance;
                float upwardSpeed = Vector3.Dot(pointVelocity, Vector3.up);

                float hoverForce = (compression * springConstant) - (upwardSpeed * dampingConstant);
                rb.AddForceAtPosition(Vector3.up * hoverForce, point.position);
            }
        }
    }

    private void ApplyUprightStabilization()
    {
        Vector3 cross = Vector3.Cross(transform.up, Vector3.up);
        Vector3 torque = (cross * uprightTorque) - (rb.angularVelocity * uprightDamping);
        rb.AddTorque(torque, ForceMode.Acceleration);
    }

    private void ApplyWalkingMovement()
    {
        if (moveInput.sqrMagnitude < 0.01f) return;

        Vector3 moveDirection;
        if (cameraTransform != null)
        {
            Vector3 camForward = cameraTransform.forward;
            Vector3 camRight = cameraTransform.right;
            camForward.y = 0;
            camRight.y = 0;
            moveDirection = (camForward.normalized * moveInput.y) + (camRight.normalized * moveInput.x);
        }
        else
        {
            moveDirection = (transform.forward * moveInput.y) + (transform.right * moveInput.x);
        }
        rb.AddForce(moveDirection.normalized * walkAcceleration, ForceMode.Acceleration);
    }

    private void ApplyRotation()
    {
        if (cameraTransform != null)
        {
            Vector3 targetForward = cameraTransform.forward;
            targetForward.y = 0;
            if (targetForward.sqrMagnitude > 0.001f)
            {
                Quaternion targetRotation = Quaternion.LookRotation(targetForward, Vector3.up);
                float angle = Quaternion.Angle(transform.rotation, targetRotation);
                if (angle > 1f)
                {
                    Vector3 cross = Vector3.Cross(transform.forward, targetForward.normalized);
                    rb.AddTorque(cross * rotationTorque, ForceMode.Acceleration);
                }
            }
        }
    }

    
}